/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

@interface PLTextView : UITextView {
    UILabel * _placeholder;
    bool  _showingPlaceholder;
}

// Image: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary

- (id)_placeholder;
- (void)dealloc;
- (void)setContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)setPlaceholderText:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)updatePlaceholder;

// Image: /System/Library/AccessibilityBundles/PhotoLibraryFramework.axbundle/PhotoLibraryFramework

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;

@end
