/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXMessagesRootGadgetViewController : PXGadgetViewController {
    PXMessagesGadgetDataSourceManager * _messagesDataSourceManager;
}

@property (nonatomic, readonly) PXMessagesGadgetDataSourceManager *messagesDataSourceManager;
@property (nonatomic) double recentPhotosHeight;

// Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore

+ (Class)gadgetSpecClass;

- (void).cxx_destruct;
- (id)initWithGadgetDataSourceManager:(id)arg1;
- (id)messagesDataSourceManager;
- (double)recentPhotosHeight;
- (void)setRecentPhotosHeight:(double)arg1;
- (void)viewDidLoad;

// Image: /System/Library/AccessibilityBundles/PhotosUICore.axbundle/PhotosUICore

+ (Class)safeCategoryBaseClass;

- (void)prepareForPresentationStyle:(long long)arg1;

@end
