/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLPhotoLibraryImageSource : PLImageSource {
    int  _imageFormat;
}

@property (nonatomic, readonly) int imageFormat;

// Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices

- (id)description;
- (unsigned long long)hash;
- (int)imageFormat;
- (id)initWithImageFormat:(int)arg1;
- (bool)isEqual:(id)arg1;
- (unsigned short)sourceIdentifier;

// Image: /System/Library/AccessibilityBundles/PhotoLibraryFramework.axbundle/PhotoLibraryFramework

+ (Class)safeCategoryBaseClass;

- (id)newImageForAsset:(id)arg1 createMetadata:(id*)arg2;

@end
