/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STBarView : UIView {
    STUsageReportGraphDataPoint * _dataPoint;
    NSArray * _sectionHeightConstraints;
    NSArray * _sectionViews;
    bool  _selected;
}

@property (nonatomic, retain) STUsageReportGraphDataPoint *dataPoint;
@property (nonatomic, copy) NSArray *sectionHeightConstraints;
@property (nonatomic, copy) NSArray *sectionViews;
@property (nonatomic) bool selected;

// Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI

- (void).cxx_destruct;
- (id)dataPoint;
- (id)initWithDataPoint:(id)arg1;
- (id)sectionHeightConstraints;
- (id)sectionViews;
- (bool)selected;
- (void)setDataPoint:(id)arg1;
- (void)setSectionHeightConstraints:(id)arg1;
- (void)setSectionViews:(id)arg1;
- (void)setSelected:(bool)arg1;
- (void)setUpSectionHeightConstraints;
- (void)setUpSections;

// Image: /System/Library/AccessibilityBundles/ScreenTimeUI.axbundle/ScreenTimeUI

+ (Class)safeCategoryBaseClass;

- (unsigned long long)_accessibilityRepresentedTimePeriod;
- (void)_accessibilitySetRepresentedTimePeriod:(unsigned long long)arg1;
- (void)_accessibilitySetUnderlyingRepresentedTimePeriod:(unsigned long long)arg1;
- (unsigned long long)_accessibilityUnderlyingRepresentedTimePeriod;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })accessibilityFrame;
- (id)accessibilityLabel;
- (bool)isAccessibilityElement;

@end
