/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STMostUsedCell : STUsageCell {
    UIImageView * _allowanceIconView;
}

@property (nonatomic, readonly) UIImageView *allowanceIconView;

// Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI

- (void).cxx_destruct;
- (id)allowanceIconView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)reloadWithSpecifier:(id)arg1 animated:(bool)arg2;
- (void)setValue:(id)arg1;

// Image: /System/Library/AccessibilityBundles/ScreenTimeUI.axbundle/ScreenTimeUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (id)accessibilityValue;

@end
