/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STScreenTimeUsageSummaryCell : STTableCell {
    STUsageSummaryView * _usageSummaryView;
}

@property (nonatomic, readonly) STUsageSummaryView *usageSummaryView;

// Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI

- (void).cxx_destruct;
- (void)_heightDidChange;
- (void)_layoutDidChangeFrom:(bool)arg1 to:(bool)arg2;
- (void)_numberOfLinesDidChangeFrom:(id)arg1 to:(id)arg2;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)setValue:(id)arg1;
- (id)usageSummaryView;

// Image: /System/Library/AccessibilityBundles/ScreenTimeUI.axbundle/ScreenTimeUI

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityAlwaysReturnsChild;
- (id)accessibilityElements;

@end
