/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STSingleLineHeaderView : STTableViewHeaderFooterView <PSHeaderFooterView> {
    PSSpecifier * _specifier;
    UILabel * _titleLabel;
}

@property (nonatomic) PSSpecifier *specifier;
@property (nonatomic, readonly) UILabel *titleLabel;

// Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI

- (void).cxx_destruct;
- (id)initWithSpecifier:(id)arg1;
- (id)initWithSpecifier:(id)arg1 useContentLayoutGuide:(bool)arg2;
- (double)preferredHeightForWidth:(double)arg1;
- (void)reloadFromSpecifier;
- (void)setSpecifier:(id)arg1;
- (id)specifier;
- (id)titleLabel;

// Image: /System/Library/AccessibilityBundles/ScreenTimeUI.axbundle/ScreenTimeUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
