/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STSingleLineDetailTextHeaderView : STSingleLineHeaderView {
    UILabel * _detailLabel;
    UIActivityIndicatorView * _spinnerView;
}

@property (readonly) UILabel *detailLabel;
@property (readonly) UIActivityIndicatorView *spinnerView;

// Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI

- (void).cxx_destruct;
- (id)detailLabel;
- (id)initWithSpecifier:(id)arg1 useContentLayoutGuide:(bool)arg2;
- (void)reloadFromSpecifier;
- (id)spinnerView;
- (void)startAnimatingSpinner;
- (void)stopAnimatingSpinner;

// Image: /System/Library/AccessibilityBundles/ScreenTimeUI.axbundle/ScreenTimeUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;

@end
