/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI
 */

@interface MCDetailsDescriptionTableCell : UITableViewCell {
    MCDetailsDescriptionView * _descView;
}

// Image: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI

- (void).cxx_destruct;
- (double)heightForTableView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 data:(id)arg3;
- (void)setUsesDynamicAlignment:(bool)arg1;

// Image: /System/Library/AccessibilityBundles/ManagedConfigurationUI.axbundle/ManagedConfigurationUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityTableViewCellText;

@end
