/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI
 */

@interface MCMoreDetailsContentView : UIView {
    UILabel * _subtitle1;
    UILabel * _subtitle2;
    UILabel * _title;
}

// Image: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI

- (void).cxx_destruct;
- (id)_textForLabel:(id)arg1 value:(id)arg2;
- (void)setCertificate:(struct __SecCertificate { }*)arg1;
- (void)setHighlighted:(bool)arg1;
- (void)setPayload:(id)arg1;
- (void)setSubtitle1Text:(id)arg1;
- (void)setSubtitle2Text:(id)arg1;
- (void)setTitleText:(id)arg1;

// Image: /System/Library/AccessibilityBundles/ManagedConfigurationUI.axbundle/ManagedConfigurationUI

+ (Class)safeCategoryBaseClass;

- (void)layoutSubviews;

@end
