/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUITitleCardSectionView : SearchUICardSectionView {
    NUIContainerBoxView * _containerView;
    UILabel * _label;
}

@property (retain) NUIContainerBoxView *containerView;
@property (retain) UILabel *label;

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

+ (bool)supportsRecyclingForCardSection:(id)arg1;

- (void).cxx_destruct;
- (id)containerView;
- (id)label;
- (void)setContainerView:(id)arg1;
- (void)setLabel:(id)arg1;
- (id)setupContentView;
- (void)updateWithRowModel:(id)arg1;

// Image: /System/Library/AccessibilityBundles/SearchUI.axbundle/SearchUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
