/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIVibrantLabel : TLKVibrantLabel

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

+ (id)textColorForSearchUIStyle:(unsigned long long)arg1;
+ (id)vibrantTextColorForSearchUIStyle:(unsigned long long)arg1;

- (id)initWithStyle:(unsigned long long)arg1;
- (void)updateWithSFRichText:(id)arg1;

// Image: /System/Library/AccessibilityBundles/SearchUI.axbundle/SearchUI

+ (Class)safeCategoryBaseClass;

- (id)_axValidateString:(id)arg1;
- (id)accessibilityLabel;
- (bool)isAccessibilityElement;

@end
