/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIScoreSummaryCardSectionView : SearchUICardSectionView <NUIContainerBoxViewDelegate> {
    TLKSplitHeaderView * _splitHeaderView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (retain) TLKSplitHeaderView *splitHeaderView;
@property (readonly) Class superclass;

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

+ (id)dragTitleForCardSection:(id)arg1;
+ (int)separatorStyleForCardSection:(id)arg1;
+ (bool)supportsRecyclingForCardSection:(id)arg1;
+ (id)titleForScoreBoard:(id)arg1 forDisplay:(bool)arg2;

- (void).cxx_destruct;
- (struct CGSize { double x1; double x2; })containerView:(id)arg1 systemLayoutSizeFittingSize:(struct CGSize { double x1; double x2; })arg2 forArrangedSubview:(id)arg3;
- (void)setSplitHeaderView:(id)arg1;
- (id)setupContentView;
- (id)splitHeaderView;
- (void)updateChevronVisible:(bool)arg1 leaveSpaceForChevron:(bool)arg2;
- (void)updateWithRowModel:(id)arg1;

// Image: /System/Library/AccessibilityBundles/SearchUI.axbundle/SearchUI

+ (Class)safeCategoryBaseClass;

- (id)_axRecordStringWithLeftTeamName:(id)arg1 score:(id)arg2 rightTeamName:(id)arg3 score:(id)arg4;
- (id)accessibilityLabel;
- (bool)isAccessibilityElement;

@end
