/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUITrailersCardSectionView : SearchUICardSectionView

@property (retain) NUIContainerStackView *contentView;

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

- (id)initWithRowModel:(id)arg1 style:(unsigned long long)arg2 feedbackDelegate:(id)arg3;
- (id)setupContentView;

// Image: /System/Library/AccessibilityBundles/SearchUI.axbundle/SearchUI

+ (Class)safeCategoryBaseClass;

@end
