/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKApplyHeroCardView : UIView {
    double  _cardBackingHeight;
    double  _cardBottomPadding;
    double  _cardHeight;
    UIView * _cardImageShadowView;
    UIImageView * _cardImageView;
    double  _cardTopPadding;
    unsigned long long  _featureIdentifier;
    bool  _usesCompactLayout;
}

// Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI

- (void).cxx_destruct;
- (id)initWithFeatureIdentifier:(unsigned long long)arg1;
- (void)layoutSubviews;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

// Image: /System/Library/AccessibilityBundles/PassKitUI.axbundle/PassKitUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
