/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKNumberPadKeyButton : PKNumericBorderButton {
    unsigned long long  _value;
}

@property (nonatomic, readonly) unsigned long long value;

// Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI

- (id)init;
- (id)initWithValue:(unsigned long long)arg1;
- (unsigned long long)value;

// Image: /System/Library/AccessibilityBundles/PassKitUI.axbundle/PassKitUI

+ (Class)safeCategoryBaseClass;

- (bool)_axIsDeleteKey;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
