/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPassPaymentCardFrontFaceView : PKPassFrontFaceView {
    UILabel * _balanceLabel;
}

// Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI

- (void).cxx_destruct;
- (void)_handleAccountChanged:(id)arg1;
- (void)_updateBalanceWithAccount:(id)arg1;
- (void)createHeaderContentViews;
- (void)dealloc;
- (void)layoutSubviews;
- (void)setShowsLiveBalance:(bool)arg1;
- (bool)showsShare;
- (id)templateForLayoutMode:(long long)arg1;

// Image: /System/Library/AccessibilityBundles/PassKitUI.axbundle/PassKitUI

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityIsAccessPass;
- (bool)_accessibilityIsApplePayCashCard;
- (bool)_accessibilityIsTransitPass;
- (id)accessibilityLabel;
- (id)accessibilityValue;
- (bool)isAccessibilityElement;

@end
