/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPhysicalCardReaderModeActivationViewController : PKExplanationViewController <PKExplanationViewDelegate, PKNFCTagReaderSessionDelegate> {
    PKAccount * _account;
    PKAccountService * _accountService;
    PKPhysicalCardActivationAnimationView * _animationView;
    PKBusinessChatController * _businessChatController;
    bool  _deviceSupportsReaderMode;
    unsigned long long  _feature;
    bool  _invalidated;
    PKPaymentPass * _paymentPass;
    PKPhysicalCard * _physicalCard;
    PKNFCTagReaderSession * _readerSession;
    PKPaymentSessionHandle * _sessionHandle;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

// Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI

- (void).cxx_destruct;
- (void)_dismiss;
- (void)_invalidate;
- (void)_presentActivationWithActivationCode:(id)arg1;
- (void)_startTagReaderSession;
- (void)_stopTagReaderSession;
- (void)dealloc;
- (void)explanationViewDidSelectSetupLater:(id)arg1;
- (id)initWithAccountService:(id)arg1 account:(id)arg2 paymentPass:(id)arg3 physicalCard:(id)arg4;
- (void)nfcTagReaderSession:(id)arg1 didDetectTags:(id)arg2;
- (void)nfcTagReaderSessionDidEndUnexpectedly:(id)arg1;
- (void)viewDidAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

// Image: /System/Library/AccessibilityBundles/PassKitUI.axbundle/PassKitUI

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (void)viewDidLoad;

@end
