/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.InCallControlsParticipantTableViewCell : UITableViewCell {
    void avatarView;
    void callDelegate;
    void cameraIcon;
    void constraintsForCameraIconVisibleState;
    void constraintsForRingButtonVisibleState;
    void delegate;
    void isAccessiblityConstraintsEnabled;
    void nameLabel;
    void nameLabelFirstBaselineLayoutConstraint;
    void ringButton;
    void subtitleLabel;
    void subtitleLabelFirstBaselineLayoutConstraint;
    void subtitleLabelLastBaselineLayoutConstraint;
}

@property (nonatomic, readonly) _TtC15ConversationKit19InCallControlButton *ringButton;

// Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit

- (void).cxx_destruct;
- (void)didTapRing:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)ringButton;
- (void)traitCollectionDidChange:(id)arg1;

// Image: /System/Library/AccessibilityBundles/ConversationKit.axbundle/ConversationKit

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end
