/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.LocalParticipantView : UIView {
    void participantView;
    void style;
}

// Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;

// Image: /System/Library/AccessibilityBundles/ConversationKit.axbundle/ConversationKit

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityIsExpanded;
- (id)_axConstraintsController;
- (id)_axGetParticipantView;
- (id)_axParticipantView;
- (void)_axSetParticipantView:(id)arg1;
- (bool)accessibilityActivate;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (bool)accessibilityPerformEscape;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (bool)isAccessibilityElement;

@end
