/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CameraEffectsKit.framework/CameraEffectsKit
 */

@interface CFXControlsViewController : UIViewController {
    UIView * _controlsContainerView;
    UIView * _effectsPickerDrawer;
    bool  _usesInternalCaptureSession;
}

@property (nonatomic) UIView *controlsContainerView;
@property (nonatomic, retain) UIView *effectsPickerDrawer;
@property (nonatomic) bool usesInternalCaptureSession;

// Image: /System/Library/PrivateFrameworks/CameraEffectsKit.framework/CameraEffectsKit

- (void).cxx_destruct;
- (id)controlsContainerView;
- (id)effectsPickerDrawer;
- (void)setControlsContainerView:(id)arg1;
- (void)setEffectsPickerDrawer:(id)arg1;
- (void)setUsesInternalCaptureSession:(bool)arg1;
- (bool)usesInternalCaptureSession;

// Image: /System/Library/AccessibilityBundles/CameraEffectsKit.axbundle/CameraEffectsKit

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (void)viewDidLoad;

@end
