/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
 */

@interface AKInkSignatureView : UIView <PKCanvasViewDelegate> {
    PKCanvasView * _canvasView;
    bool  _hasStrokes;
    PKInk * _ink;
    PKDrawing * _latestDrawing;
    UIColor * _strokeColor;
}

@property (retain) PKCanvasView *canvasView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property bool hasStrokes;
@property (readonly) unsigned long long hash;
@property (copy) PKInk *ink;
@property (retain) PKDrawing *latestDrawing;
@property (nonatomic, retain) UIColor *strokeColor;
@property (readonly) Class superclass;

// Image: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit

- (void).cxx_destruct;
- (void)_commonInit;
- (void)_updateInk;
- (id)canvasView;
- (void)clear;
- (struct CGPath { }*)copyPotracedPathAndReturnDrawing:(id*)arg1;
- (bool)hasStrokes;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)ink;
- (id)latestDrawing;
- (void)layoutSubviews;
- (void)setCanvasView:(id)arg1;
- (void)setHasStrokes:(bool)arg1;
- (void)setInk:(id)arg1;
- (void)setLatestDrawing:(id)arg1;
- (void)setStrokeColor:(id)arg1;
- (id)strokeColor;
- (void)teardown;

// Image: /System/Library/AccessibilityBundles/AnnotationKit.axbundle/AnnotationKit

+ (Class)safeCategoryBaseClass;

- (id)_axDirectTouchTimer;
- (void)_axStopDirectTouch;
- (void)_setAXDirectTouchTimer:(id)arg1;
- (bool)accessibilityActivate;
- (struct CGPoint { double x1; double x2; })accessibilityActivationPoint;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (void)canvasViewDidStartNewStroke:(id)arg1;
- (void)canvasViewDrawingDidChange:(id)arg1;
- (bool)isAccessibilityElement;

@end
