/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 */

@interface CCUIScrollView : UIScrollView

@property (nonatomic) <CCUIScrollViewDelegate> *delegate;

// Image: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI

- (bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;

// Image: /System/Library/AccessibilityBundles/ControlCenterUI.axbundle/ControlCenterUI

+ (Class)safeCategoryBaseClass;

- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_accessibilityContentInset;

@end
