/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSUIRegulatoryPane : PSEditingPane {
    UIImageView * _primaryImageView;
    UIScrollView * _scrollView;
}

// Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI

- (void).cxx_destruct;
- (bool)handlesDoneButton;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (bool)shouldInsetContent;
- (void)viewDidBecomeVisible;

// Image: /System/Library/AccessibilityBundles/PreferencesUI.axbundle/PreferencesUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (bool)isAccessibilityElement;

@end
