/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSUIColorTemperatureSliderTableCell : PSSliderTableCell {
    UILabel * _coolerLabel;
    double  _horizontalMargin;
    double  _verticalMargin;
    UILabel * _warmerLabel;
}

// Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)layoutSubviews;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

// Image: /System/Library/AccessibilityBundles/PreferencesUI.axbundle/PreferencesUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (id)accessibilityValue;

@end
