/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CARDNDUI.framework/CARDNDUI
 */

@interface CARDNDLearnMoreViewController : UIViewController {
    NSLayoutConstraint * _bottomMarginConstraint;
    UITextView * _textView;
}

@property (nonatomic, retain) NSLayoutConstraint *bottomMarginConstraint;
@property (nonatomic, retain) UITextView *textView;

// Image: /System/Library/PrivateFrameworks/CARDNDUI.framework/CARDNDUI

- (void).cxx_destruct;
- (id)bottomMarginConstraint;
- (void)setBottomMarginConstraint:(id)arg1;
- (void)setTextView:(id)arg1;
- (id)textView;
- (void)viewSafeAreaInsetsDidChange;

// Image: /System/Library/AccessibilityBundles/CARDNDUI.axbundle/CARDNDUI

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (void)viewDidLoad;

@end
