/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager
 */

@interface DOCFlexibleBarButtonItem : UIBarButtonItem {
    NSDictionary * _variants;
}

// Image: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager

- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 image:(id)arg2 smallImage:(id)arg3 systemItem:(long long)arg4 target:(id)arg5 action:(SEL)arg6;
- (void)setEnabled:(bool)arg1;

// Image: /System/Library/AccessibilityBundles/DocumentManager.axbundle/DocumentManager

+ (Class)safeCategoryBaseClass;

- (id)variantForTraitCollection:(id)arg1;

@end
