/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 */

@interface CCUIMenuModuleStackView : UIStackView

// Image: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit

- (void)layoutSubviews;

// Image: /System/Library/AccessibilityBundles/ControlCenterUI.axbundle/ControlCenterUI

+ (Class)safeCategoryBaseClass;

- (bool)shouldGroupAccessibilityChildren;

@end
