/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
 */

@interface CCUIAppLauncherViewController : CCUIMenuModuleViewController {
    SBFApplication * _application;
    SCUIAssetProvider * _assetProvider;
    CCUIAppLauncherModule * _module;
}

@property (nonatomic) CCUIAppLauncherModule *module;

// Image: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit

- (void).cxx_destruct;
- (void)_activateApplicationForShortcutItem:(id)arg1;
- (void)_addActionForShortcutItem:(id)arg1;
- (void)_updateApplicationShortcutsActions;
- (void)buttonTapped:(id)arg1 forEvent:(id)arg2;
- (void)didBeginInteraction;
- (id)module;
- (void)setModule:(id)arg1;
- (bool)shouldBeginTransitionToExpandedContentModule;
- (void)viewDidLoad;

// Image: /System/Library/AccessibilityBundles/ControlCenterUIKit.axbundle/ControlCenterUIKit

+ (Class)safeCategoryBaseClass;

- (id)_accessibilityControlCenterButtonIdentifier;
- (id)_accessibilityControlCenterButtonLabel;
- (bool)_accessibilityControlCenterShouldExpandContentModule;

@end
