/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface MiroMovieView : UIView

// Image: /System/Library/PrivateFrameworks/Memories.framework/Memories

+ (Class)layerClass;

- (id)avPlayerLayer;
- (void)cleanupPlayerLayerAttributes;
- (void)configurePlayerLayerAttributes;
- (id)player;
- (void)setPlayer:(id)arg1;

// Image: /System/Library/AccessibilityBundles/Memories.axbundle/Memories

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (id)accessibilityValue;
- (bool)isAccessibilityElement;

@end
