/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKBreatheEntryModel : NTKTimelineEntryModel {
    bool  _isLoading;
    bool  _isLocked;
    unsigned long long  _minutesBreathed;
}

@property (nonatomic) bool isLoading;
@property (nonatomic) bool isLocked;
@property (nonatomic) unsigned long long minutesBreathed;

// Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion

+ (id)companionModel;
+ (bool)familySupportsLiveData:(long long)arg1;
+ (id)lockedEntryModel;
+ (id)modelWithActivitySummary:(id)arg1;
+ (bool)supportsFlowerImages;

- (id)_circularMediumTemplate;
- (id)_circularSmallTemplate;
- (id)_extraLargeTemplate;
- (id)_modularSmallTemplate;
- (id)_signatureBezelTemplate;
- (id)_signatureCornerTemplate;
- (id)_utilitarianSmallTemplate;
- (bool)isLoading;
- (bool)isLocked;
- (unsigned long long)minutesBreathed;
- (void)setIsLoading:(bool)arg1;
- (void)setIsLocked:(bool)arg1;
- (void)setMinutesBreathed:(unsigned long long)arg1;

// Image: /System/Library/AccessibilityBundles/NanoTimeKitCompanion.axbundle/NanoTimeKitCompanion

+ (Class)safeCategoryBaseClass;

- (id)_signatureCircularTemplate;
- (id)templateForComplicationFamily:(long long)arg1;

@end
