/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKCFaceDetailSpacerCell : NTKCDetailTableViewCell

// Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion

+ (double)actionExtraRowHeight;
+ (id)reuseIdentifier;
+ (double)rowHeight;

- (double)rowHeight;

// Image: /System/Library/AccessibilityBundles/NanoTimeKitCompanion.axbundle/NanoTimeKitCompanion

+ (Class)safeCategoryBaseClass;

- (bool)accessibilityElementsHidden;
- (bool)isAccessibilityElement;

@end
