/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HeartRhythmUI.framework/HeartRhythmUI
 */

@interface HRSimulatedAtrialFibrillationNotificationView : UIView {
    HRSimulatedAtrialFibrillationQuickLookView * _simView;
}

@property (nonatomic, retain) HRSimulatedAtrialFibrillationQuickLookView *simView;

// Image: /System/Library/PrivateFrameworks/HeartRhythmUI.framework/HeartRhythmUI

- (void).cxx_destruct;
- (id)init;
- (void)layoutSubviews;
- (void)setSimView:(id)arg1;
- (id)simView;

// Image: /System/Library/AccessibilityBundles/HeartRhythmUI.axbundle/HeartRhythmUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
